# ai-engine/engine/nodes/create_pull_request.py

import logging
import httpx

from engine.state import AgentState
from engine.nodes.utils import emit

logger = logging.getLogger(__name__)


def create_pull_request(state: AgentState) -> dict:
    """
    Node 9: Open a PR from the fix branch → default branch via GitHub API.
    """
    emit(state, "node_start", "pr", iteration=state["current_iteration"])

    if state.get("read_only"):
        emit(state, "node_end", "pr", read_only=True)
        return {}

    github_token = state.get("github_token")
    owner = state["repo_owner"]
    repo = state["repo_name"]
    branch_name = state["branch_name"]
    default_branch = state.get("default_branch", "main")
    commits = state.get("commits", [])

    if not commits:
        logger.info("No commits to create PR for")
        emit(state, "node_end", "pr", push_attempted=False)
        return {}

    if not github_token:
        logger.warning("No GitHub token — cannot create PR")
        emit(state, "node_end", "pr", push_attempted=False)
        return {}

    fixes = state.get("fixes", [])
    fix_summary = "\n".join([
        f"- `{f.file}:{f.line}` — {f.bug_type.value}: {f.commit_message}"
        for f in fixes[:20]
    ])

    pr_body = f"""## 🤖 AI-AGENT Auto-Fix

This PR was automatically generated by CI Healer.

### Fixes Applied ({len(commits)} commits)
{fix_summary}

> Generated by CI Healer Agent
"""

    try:
        with httpx.Client(timeout=15) as client:
            response = client.post(
                f"https://api.github.com/repos/{owner}/{repo}/pulls",
                headers={
                    "Authorization": f"Bearer {github_token}",
                    "Accept": "application/vnd.github+json",
                },
                json={
                    "title": f"[AI-AGENT] Auto-fix: {len(fixes)} issues resolved",
                    "body": pr_body,
                    "head": branch_name,
                    "base": default_branch,
                },
            )

        if response.status_code == 201:
            pr_url = response.json()["html_url"]
            logger.info("PR created: %s", pr_url)
            emit(state, "node_end", "pr", pr_url=pr_url, push_attempted=True)
            return {"pr_url": pr_url}

        logger.error("PR creation failed: %s — %s", response.status_code, response.text)
        emit(state, "node_end", "pr", push_attempted=True)
        return {}

    except Exception as e:
        logger.error("PR creation exception: %s", e)
        emit(state, "node_end", "pr", push_attempted=True)
        return {}
